echo "###############################################"
echo "# gunakan dengan bijak gan salam hacker #"
echo "#                                             #"
echo "# =>    https://bit.ly/3zpH5qh   <=        #"
echo "#   bonus:    https://bit.ly/3aXz0jq      #"
echo "#  silahkan anda salin lalu kirim ke target   #"
echo "###############################################"